### PR TITLE
Update the thor and tilt dependencies

### PR DESCRIPTION
**Pull request by henderea**
I ran `rake spec`, and everything passed.

### CODE REVIEW

**Comment by henderea** [comment]
Hmm, seems `listen` doesn't like the ruby version.

**Comment by henderea** [comment]
There, looks like i fixed the travis issue.

**Comment by colinta** [comment]
Nice!

**Comment by colinta** [comment]
Available in 1.0.1 - thanks!

**Comment by colinta** [comment]
@henderea I added you as a collaborator, if you're not interested or don't have time I understand!

**Comment by henderea** [comment]
@colinta i don't mind, but i don't know that i'll do much of anything on the core stuff. i'm not all that familiar with xcode project systems or nib/storyboard source xml

**Pull request merged**
