### PR TITLE
Fixes issue with subfolders in resources folder not being recognized in the resulting xcode project

### LINKED ISSUE #78: Subfolders in /resources don't seem to be referenced correctly in resulting xcode project
Here's my folder structure...

screenshot 2015-01-20 12 35 50

And the resulting xcode project has the files in red.

Moving the files out of the subfolder makes the xcode file reference turn black and the file is accessible. It seems like xcode isn't getting the correct path for the resource file:

```xml
<key>9CBABA3531C7B6D591F332AE</key>
<dict>
  <key>includeInIndex</key>
  <string>1</string>
  <key>isa</key>
  <string>PBXFileReference</string>
  <key>lastKnownFileType</key>
  <string>file.xib</string>
  <key>path</key>
  <string>ActivityFavouriteTableViewCell.xib</string>
  <key>sourceTree</key>
  <string>&lt;group&gt;</string>
</dict>
```
Should be: 

```xml
<key>9CBABA3531C7B6D591F332AE</key>
<dict>
  <key>includeInIndex</key>
  <string>1</string>
  <key>isa</key>
  <string>PBXFileReference</string>
  <key>lastKnownFileType</key>
  <string>file.xib</string>
  <key>name</key>
  <string>ActivityFavouriteTableViewCell.xib</string>
  <key>path</key>
  <string>assets/ActivityFavouriteTableViewCell.xib</string>
  <key>sourceTree</key>
  <string>&lt;group&gt;</string>
</dict>
```

### PR DESCRIPTION
**Pull request by markrickert**
Closes #78

### CODE REVIEW

**Comment by colinta** [comment]
As much as I love a simple `sub`, I wonder if a more thorough solution is warranted.  I just never really feel good about strings-as-paths:

```ruby
require 'pathname'

# in the method body, can be reused
resourcespath = Pathname.new '/path/to/resources/'

# in the block body
  filepath = Pathname.new file
  location = filepath.relative_path_from(resourcespath).to_s
  # => assets/file.ext
  group.new_reference(location)
```

**Comment by markrickert** [comment]
totally understand... let me test that methodology out.

**Comment by markrickert** [comment]
Looks like it works :)

**Comment by colinta** [comment]
Sweet!

**Comment by colinta** [comment]
Avail in 0.7.2

**Comment by markrickert** [comment]
:+1: Thanks!

**Pull request merged**
